// Chromux v1 — main-window preload. Narrow, explicit bridge; no node in the page.
'use strict';

const { contextBridge, ipcRenderer } = require('electron');
const path = require('path');
const yaml = require('js-yaml');
const shortcutInput = require('./shortcut-input');

contextBridge.exposeInMainWorld('chromux', {
  // pty
  ptyCreate: (opts) => ipcRenderer.invoke('pty-create', opts),
  ptyInput: (id, data) => ipcRenderer.send('pty-input', { id, data }),
  ptyResize: (id, cols, rows) => ipcRenderer.send('pty-resize', { id, cols, rows }),
  ptyKill: (id) => ipcRenderer.send('pty-kill', { id }),
  onPtyData: (cb) => ipcRenderer.on('pty-data', (_e, m) => cb(m)),
  onPtyExit: (cb) => ipcRenderer.on('pty-exit', (_e, m) => cb(m)),

  // capture + delivery
  capturePrepare: (payload, pngBase64) => ipcRenderer.invoke('capture-prepare', { payload, pngBase64 }),
  onCaptureControlRequest: (cb) => ipcRenderer.on('capture-control-request', (_e, message) => cb(message)),
  captureControlRespond: (message) => ipcRenderer.send('capture-control-response', message),
  captureRecordChunk: (message) => ipcRenderer.send('capture-record-chunk', message),
  captureRecordComplete: (message) => ipcRenderer.send('capture-record-complete', message),
  deliverClaude: (opts) => ipcRenderer.invoke('deliver-claude', opts),
  deliverCancel: (deliveryId) => ipcRenderer.send('deliver-cancel', { deliveryId }),
  onDeliverOutput: (cb) => ipcRenderer.on('deliver-output', (_e, m) => cb(m)),
  onDeliverClose: (cb) => ipcRenderer.on('deliver-close', (_e, m) => cb(m)),
  logFiledrop: (opts) => ipcRenderer.send('log-filedrop', opts),
  readDeliveryLog: () => ipcRenderer.invoke('read-delivery-log'),
  favoritesRead: () => ipcRenderer.invoke('favorites-read'),
  favoritesReplace: (records) => ipcRenderer.invoke('favorites-replace', records),
  projectsRead: () => ipcRenderer.invoke('projects-read'),
  projectsReplace: (records) => ipcRenderer.invoke('projects-replace', records),
  projectScaffolderConfig: () => ipcRenderer.invoke('project-scaffolder-config'),
  projectScaffolderPreview: (request) => ipcRenderer.invoke('project-scaffolder-preview', request || {}),
  projectScaffolderSetRoot: (root) => ipcRenderer.invoke('project-scaffolder-root-set', root),
  projectScaffolderCreate: (request) => ipcRenderer.invoke('project-scaffolder-create', request || {}),
  promptHistoryRead: (cwd) => ipcRenderer.invoke('prompt-history-read', cwd),
  promptHistoryAppend: (cwd, entry) => ipcRenderer.invoke('prompt-history-append', cwd, entry),
  promptHistoryDelete: (cwd, id) => ipcRenderer.invoke('prompt-history-delete', cwd, id),
  promptHistoryClear: (cwd) => ipcRenderer.invoke('prompt-history-clear', cwd),
  clipboardWriteText: (text) => ipcRenderer.invoke('clipboard-write-text', text),
  projectConfig: (cwd) => ipcRenderer.invoke('project-config', cwd),
  projectScriptResolve: (cwd, script) => ipcRenderer.invoke('project-script-resolve', { cwd, script }),
  previewProbe: (url) => ipcRenderer.invoke('preview-probe', url),
  gitRoot: (cwd) => ipcRenderer.invoke('git-root', cwd),
  gitDiffSummary: (cwd) => ipcRenderer.invoke('git-diff-summary', cwd),
  gitRepositoriesRead: () => ipcRenderer.invoke('git-repositories-read'),
  gitRepositoryObserve: (request) => ipcRenderer.invoke('git-repository-observe', request || {}),
  gitRepositoryForget: (repositoryId) => ipcRenderer.invoke('git-repository-forget', repositoryId),
  gitWorktreeInventory: (request) => ipcRenderer.invoke('git-worktree-inventory', request || {}),
  gitWorktreeDiff: (request) => ipcRenderer.invoke('git-worktree-diff', request || {}),
  gitWorktreeStage: (request) => ipcRenderer.invoke('git-worktree-stage', request || {}),
  gitWorktreeUnstage: (request) => ipcRenderer.invoke('git-worktree-unstage', request || {}),
  gitWorktreeCommitPreview: (request) => ipcRenderer.invoke('git-worktree-commit-preview', request || {}),
  gitWorktreeCommit: (request) => ipcRenderer.invoke('git-worktree-commit', request || {}),
  gitWorktreeFetch: (request) => ipcRenderer.invoke('git-worktree-fetch', request || {}),
  gitWorktreePull: (request) => ipcRenderer.invoke('git-worktree-pull', request || {}),
  gitWorktreePublish: (request) => ipcRenderer.invoke('git-worktree-publish', request || {}),
  gitWorktreePush: (request) => ipcRenderer.invoke('git-worktree-push', request || {}),
  gitWorktreeSync: (request) => ipcRenderer.invoke('git-worktree-sync', request || {}),
  vercelCapability: (location) => ipcRenderer.invoke('vercel-capability', location || {}),
  vercelConnectionsRead: () => ipcRenderer.invoke('vercel-connections-read'),
  vercelConnectCli: (request) => ipcRenderer.invoke('vercel-connect-cli', request || {}),
  vercelConnectToken: (request) => ipcRenderer.invoke('vercel-connect-token', request || {}),
  vercelConnectionValidate: (request) => ipcRenderer.invoke('vercel-connection-validate', request || {}),
  vercelConnectionRemove: (profileId) => ipcRenderer.invoke('vercel-connection-remove', profileId),
  vercelProjectDiscover: (location) => ipcRenderer.invoke('vercel-project-discover', location || {}),
  vercelProjectsRead: () => ipcRenderer.invoke('vercel-projects-read'),
  vercelProjectSave: (request) => ipcRenderer.invoke('vercel-project-save', request || {}),
  vercelProjectRemove: (key) => ipcRenderer.invoke('vercel-project-remove', key),
  resourcesList: () => ipcRenderer.invoke('resources-list'),
  resourcesCancel: (requestId) => ipcRenderer.invoke('resources-cancel', requestId),
  resourcesForceRelease: (leaseId) => ipcRenderer.invoke('resources-force-release', leaseId),
  resourcesSetCapacity: (value) => ipcRenderer.invoke('resources-set-capacity', value),

  // popups intercepted in main → review queue
  onWebviewPopup: (cb) => ipcRenderer.on('webview-popup', (_e, m) => cb(m)),

  // external terminal/agent-session detection
  detectExternal: () => ipcRenderer.invoke('detect-external'),
  detectPtyAgents: () => ipcRenderer.invoke('detect-pty-agents'),

  // utilities
  toYaml: (obj) => yaml.dump(obj, { lineWidth: 120, noRefs: true }),
  fileExists: (p) => ipcRenderer.invoke('file-exists', p),
  projectHtmlIndex: (opts) => ipcRenderer.invoke('project-html-index', opts || {}),
  resolveProjectHtml: (opts) => ipcRenderer.invoke('resolve-project-html', opts || {}),
  pickDirectory: () => ipcRenderer.invoke('pick-directory'),
  wslListDistros: () => ipcRenderer.invoke('wsl-list-distros'),
  wslRefreshReadiness: () => ipcRenderer.invoke('wsl-refresh-readiness'),
  wslSelectDistro: (distro) => ipcRenderer.invoke('wsl-select-distro', distro),
  pathToRuntime: (path, distro) => ipcRenderer.invoke('path-to-runtime', { path, distro }),
  pathToHost: (location) => ipcRenderer.invoke('path-to-host', location),
  revealPath: (p) => ipcRenderer.send('reveal-path', { p }),
  setWindowButtonPosition: (position) => ipcRenderer.send('set-window-button-position', position),
  getEnv: () => ipcRenderer.invoke('get-env'),
  restartWithDevMode: (opts) => ipcRenderer.invoke('restart-with-dev-mode', opts || {}),
  setPreventSleep: (enabled) => ipcRenderer.invoke('prevent-sleep-set', enabled),
  onPreventSleepStatus: (cb) => ipcRenderer.on('prevent-sleep-status', (_e, status) => cb(status)),
  checkUpdates: (opts) => ipcRenderer.invoke('check-updates', opts || {}),
  checkCodexUpdate: (opts) => ipcRenderer.invoke('codex-update-check', opts || {}),
  installCodexUpdate: () => ipcRenderer.invoke('codex-update-install'),
  onCodexUpdateProgress: (cb) => ipcRenderer.on('codex-update-progress', (_e, m) => cb(m)),
  openUpdateRelease: (opts) => ipcRenderer.invoke('open-update-release', opts || {}),
  openSecurityResource: (resource) => ipcRenderer.invoke('open-security-resource', resource),
  installUpdate: (opts) => ipcRenderer.invoke('install-update', opts || {}),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, m) => cb(m)),
  saveRestoreSnapshot: (opts) => ipcRenderer.invoke('save-restore-snapshot', opts || {}),
  getRestoreSnapshot: () => ipcRenderer.invoke('get-restore-snapshot'),
  markRestoreSnapshotConsumed: (opts) => ipcRenderer.invoke('mark-restore-snapshot-consumed', opts || {}),
  resolveRestoreSessions: (opts) => ipcRenderer.invoke('resolve-restore-sessions', opts || {}),
  confirmAppClose: (opts) => ipcRenderer.invoke('confirm-app-close', opts || {}),
  onLifecycleConfirmClose: (cb) => ipcRenderer.on('lifecycle-confirm-close', (_e, m) => cb(m)),
  reportShortcutFocusContext: (payload) => ipcRenderer.send('shortcut-focus-context', payload || {}),
  shortcutAction: (input) => shortcutInput.chromuxShortcutAction(input || {}, process.platform),
  shortcutContextKind: (context) => shortcutInput.classifyShortcutFocusContext(context || {}),
  shortcutContextDisabledReason: (context) => shortcutInput.shortcutContextDisabledReason(context || {}),
  onShortcutDebugInput: (cb) => ipcRenderer.on('shortcut-debug-input', (_e, m) => cb(m)),
  onShortcutActivateSessionIndex: (cb) => ipcRenderer.on('shortcut-activate-session-index', (_e, m) => cb(m)),
  onShortcutFocusNextQueueItem: (cb) => ipcRenderer.on('shortcut-focus-next-queue-item', () => cb()),
  onShortcutToggleBrowser: (cb) => ipcRenderer.on('shortcut-toggle-browser', () => cb()),
  onShortcutBrowserFullscreen: (cb) => ipcRenderer.on('shortcut-browser-fullscreen', () => cb()),
  onShortcutOpenNewSession: (cb) => ipcRenderer.on('shortcut-open-new-session', () => cb()),
  onShortcutCreateProject: (cb) => ipcRenderer.on('shortcut-create-project', () => cb()),
  onShortcutOpenDetectModal: (cb) => ipcRenderer.on('shortcut-open-detect-modal', () => cb()),
  onShortcutOpenComposer: (cb) => ipcRenderer.on('shortcut-open-composer', () => cb()),
  webviewPreloadPath: 'file://' + path.join(__dirname, 'webview-preload.js'),
});

if (process.env.CHROMUX_E2E) {
  contextBridge.exposeInMainWorld('chromuxTest', {
    sendHostInput: (input) => ipcRenderer.invoke('test-send-host-input', input),
    shortcutRouteLog: () => ipcRenderer.invoke('test-shortcut-route-log'),
    classifyPtyAgentDescendants: (payload) => ipcRenderer.invoke('test-classify-pty-agent-descendants', payload || {}),
    clipboardReadText: () => ipcRenderer.invoke('test-clipboard-read-text'),
    restorePayload: (payload) => ipcRenderer.invoke('test-restore-payload', payload || {}),
  });
}
